### ISSUE TITLE
Resource not found mailchimp error

### ISSUE THREAD

**Issue by duerrsimon** [danielstieber/SubscribeToMailchimp#11]
I am having troubles using this module. 

The test for the api settings works and correctly returns the data entered in mailchimp but when i try to subscribe a user it does not work. I dumped the response text and I get 
"{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Resource Not Found","status":404,"detail":"The reques ...
The request is made to https://us4.api.mailchimp.com/3.0/lists/a924e509dd/members 

I am on localhost at the moment but I guess that should not matter? Anybody had this problem so far?

**Comment by ml-eds** [comment]
My guess is that this is a result of open issue #10

**Comment by duerrsimon** [comment]
Yes. I just tried the 0.0.6 version on the dev branch and subscribing works for me now! Thanks for addressing this so quickly @ml-eds @danielstieber

**Comment by danielstieber** [comment]
all thanks to @ml-eds ! :)
