### ISSUE TITLE
Subscribe with ADDRESS merge_field not working

### ISSUE THREAD

**Issue by ml-eds** [danielstieber/SubscribeToMailchimp#5]
Create new list members with activated ADDRESS merge field does not work.

According to [https://us1.api.mailchimp.com/schema/3.0/Lists/Members/MergeField.json](https://us1.api.mailchimp.com/schema/3.0/Lists/Members/MergeField.json) ADDRESS is an object. On PHP side this would be an array within the array of parameter $merge_fields of method _subscribe_.

The following code effectively removes the array value within $merge_fields

```            
          foreach ($merge_fields as $k => $v) {
                if(!empty(trim($v))) { // avoid to override data of existing leads with empty field values
                    $param['merge_fields'][$k] = $v;
                }
            }
```

**Comment by danielstieber** [comment]
Thanks a lot for your help! Haven't used the address field yet, but this totally makes sense. Please check my review, so I can merge it in.

**Comment by ml-eds** [comment]
Commit https://github.com/danielstieber/SubscribeToMailchimp/pull/6/commits/6938e3168e0faef799c3ea9974651f75cfd5720a addresses your change request.
